sudo: false
cache:
  directories:
    - node_modules
    - "$HOME/google-cloud-sdk/"
jobs:
  include:
    - stage: test
      language: node_js
      script:
        - make test
    - stage: deploy
      language: python
      python:
        - "3.8"
      env:
        - PATH=$PATH:${HOME}/google-cloud-sdk/bin
          PYTHONPATH=${PYTHONPATH}:${GAE_PYTHONPATH} CLOUDSDK_CORE_DISABLE_PROMPTS=1
      before_install:
        - pip uninstall crcmod
        - pip install --no-cache-dir -U crcmod
        - pip install httplib2
        - if [ "$TRAVIS_BRANCH" != "master" -o "$TRAVIS_PULL_REQUEST" != "false" ]; then travis_terminate 0; fi
        - openssl aes-256-cbc -K $encrypted_3108ac7e9a1f_key -iv $encrypted_3108ac7e9a1f_iv
          -in .travis/credentials.tar.gz.enc -out credentials.tar.gz -d
        - gcloud version || true
        - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; curl https://sdk.cloud.google.com | bash; fi
        - source /home/travis/google-cloud-sdk/path.bash.inc
        - tar -xzf credentials.tar.gz
        - gcloud auth activate-service-account --key-file client-secret.json
      script:
        - make deploy
        - .travis/sentry-release.sh
