name: deploy & test

on:
  push:
    branches:
      - master
  pull_request:

env:
  NODE_OPTIONS: '--max-old-space-size=4096'

jobs:
  test:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - run: make test

  deploy:
    # needs: test
    runs-on: 'ubuntu-latest'
    environment: 'gcp - project=sourcemapsio'
    steps:
      - id: setup-gcloud
        name: 'Setup gcloud'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 400.0.0'

      - id: auth-gcloud
        name: 'Auth gcloud'
        env:
          SERVICE_KEY_BASE64: ${{ secrets.GCLOUD_SERVICE_KEY }}
        run: |  
          echo $SERVICE_KEY_BASE64 | base64 --decode > service-key.json
          gcloud auth activate-service-account --key-file service-key.json

      - id: checkout
        name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - uses: getsentry/action-setup-volta@e4939d337b83760d13a9d7030a6f68c9d0ee7581 # v2.0.0

      - id: deploy
        name: 'Deploy to GCP Cloud Functions'
        env:        
          GCLOUD_APP_BUCKET: ${{ secrets.GCLOUD_APP_BUCKET }}
          GCLOUD_DATA_BUCKET: ${{ secrets.GCLOUD_DATA_BUCKET }}
          GCLOUD_PROJECT: ${{ secrets.GCLOUD_PROJECT }}
          GCLOUD_WWW_BUCKET: ${{ secrets.GCLOUD_WWW_BUCKET }}
          REACT_APP_SENTRY_DSN: ${{ vars.REACT_APP_SENTRY_DSN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_CLIENT_PROJECT: ${{ secrets.SENTRY_CLIENT_PROJECT }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        run: |
          make deploy
          .github/sentry-release.sh
